FROM python:2.7
RUN pip install jupyter

RUN apt-get update && apt-get install -y --no-install-recommends \
		git \
		openssh-client \
		\
		procps \
	&& rm -rf /var/lib/apt/lists/*



EXPOSE 8888
CMD [ "jupyter", "notebook", "--ip='0.0.0.0'",  "--allow-root" ]
